- name: Add conf to the cinder.conf file
  ini_file: 
    dest: /etc/cinder/cinder.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: DEFAULT, option: notification_driver, value: messagingv2 }

- name: Restart the Block Storage services
  service: name={{ item }} state=restarted
  with_items:
    - cinder-volume
