- name: Add conf to the cinder.conf file
  ini_file: 
    dest: /etc/ceilometer/ceilometer.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: "filter:keystoneauth", option: operator_roles, value: "admin, user, ResellerAdmin"}
    - { section: "pipeline:main", option: pipeline, value: "catch_errors gatekeeper healthcheck proxy-logging"}
